# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e906f5dd8b1c97e4864129bcf72750717fb3dfe7057499c3623e169e8f78412b788b4224c075b9512b8478fc1f6801082ef6afa42a60da6d6e0fb1853dc3f57

test:
  secret_key_base: f8e7b60346a0181ad8b52136de9b4095362999487a5a8094bea8ba9e879f26adc347d6f046f8aaf02a2ca3ab7f1501b83d870f71c6d3b9f77dea0522af9ff5ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
